# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2.1
orbs:
  codecov: codecov/codecov@3.2.3
jobs:
  
  upload-to-codecov:
    docker:
      - image: cimg/base:stable
    steps:
      - codecov/upload
      - run: Ls

  composer-install:
    docker:
      - image: circleci/php:7.3-browsers
    steps:
    - checkout
    - run: composer install -n --prefer-dist

workflows:
  main-workflow:
    jobs:
      - composer-install
      - upload-to-codecov
      
    