# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    docker:
    - image: circleci/php:7.3-browsers

    working_directory: ~/repo

    steps:
    - checkout
    - run: composer install -n --prefer-dist
    - store_test_results:
      path: test-results

  deploy:
    docker:
    - image: circleci/python:3.6.1

    working_directory: ~/repo

    steps:
    