# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
orbs:
  codecov: codecov/codecov@3.2.3
jobs:
  build:
    docker:
    - image: circleci/php:7.3-browsers

    working_directory: ~/repo

    steps:
    - checkout
    - run: composer install -n --prefer-dist
    - codecov/upload:
          file: {{ coverage_report_filepath }}
      
    